icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
idle_bg = "#222222"
info_bg = "#222222"
good_bg = "#222222"
warning_bg = "#222222"
critical_bg = "#222222"
idle_fg = "#bababa"
info_fg = "#bababa"
separator = " "
separator_bg = "#222222"

[[block]]
block = "music"
player = "spotify"
buttons = ["play"]
max_width = 120

[[block]]
block = "sound"
interval = 1

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
bitrate = false
ip = true
speed_up = false
speed_down = false
interval = 1

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 1

[[block]]
block = "disk_space"
path = "/home"
alias = "~/"
info_type = "available"
unit = "GB"
interval = 1

[[block]]
block = "battery"
interval = 1
show = "both"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %R"
